### ISSUE TITLE
PAUSD Scraping isn't working

### ISSUE THREAD

**Issue by rselwyn** [team8/attendance#45]
The code to scrape the PAUSD name DB isn't working.  I have tested this with several student IDs known to not be in the system.

**Comment by Naqu6** [comment]
No it worked before the merge.

No my fault

**Comment by Naqu6** [comment]
Still working on card scanning

**Comment by Naqu6** [comment]
I know whats wrong. merging card scanning with master
(Some one deleted a line of my code)

**Comment by rselwyn** [comment]
I would prefer to close this after the fix has been merged into master.

**Comment by Naqu6** [comment]
I just merged the branch.

**Comment by DeckardKane** [comment]
Just as an FYI, these changes have not gone live yet.

**Comment by Naqu6** [comment]
I fixed it and merge the issue.
Robbie, do not open this again.

**Comment by rselwyn** [comment]
@Naqu6 Commit number(s)?

**Comment by Naqu6** [comment]
Portals merge to master

**Comment by rselwyn** [comment]
Ryan, this still doesn't work.  I just confirmed with multiple student IDs that are known to not be in the system.

**Comment by Naqu6** [comment]
Pushing @ robo today.
When Peter merge, he selected the wrong file and deleted an import.

**Comment by rselwyn** [comment]
Then this can be closed during robotics.  Please don't close until it has been merged and you have a PR ref.

**Comment by Naqu6** [comment]
Stop

**Comment by DeckardKane** [comment]
@Naqu6: In the most recent merge? I definitely did not do that, weren't you the one who merged (I removed branch protection so you could get it done, IIRC)? Or are you referring to an older merge?

**Comment by DeckardKane** [comment]
And on a general note, these issue wars *need* to stop. To be clear: I mean *both* of you need to stop antagonizing each other over this issue, please try to display gracious professionalism and work together like the teammates that you are. Let me know if you need my assistance in getting the bug sorted out.

**Comment by rselwyn** [comment]
Honestly, @Naqu6 I'm not trying to have a war here.  **As of now, the fix still hasn't been merged into master.**  This issue was originally closed 7 days ago.  I hope you see the issue here.

**Comment by DeckardKane** [comment]
Please be mature (both of you) or I will lock this conversation. As of right now, this has not yet been fixed. I get that you guys are busy, so I'm going to fix portal and merge it.

**Comment by DeckardKane** [comment]
Was working on the error, @Naqu6, if you made changes to the database, that's totally fine, but it may be a good idea to tell us so we know to make migrations (and specifically, what you populated it with, I want to make sure I do it properly on the live server).

**Comment by rselwyn** [comment]
Status update on this?

**Comment by Naqu6** [comment]
Working on this after build season.

**Comment by rselwyn** [comment]
This can be closed (this portal doesn't even exist any more).
